name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: devskale/huggingface-sync-action@v1
      with:
        github_repo_id: devskale/tst
        huggingface_repo_id: woodmastr/tst
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN }}
